### ISSUE TITLE
Make it more like RAMP's geosearch :)

### ISSUE THREAD

**Issue by AleksueiR** [RAMP-PCAR/geosearch#1]
RAMP uses http://geogratis.gc.ca/services/geoname/en/geonames.json when searching for location names:
> http://geogratis.gc.ca/services/geoname/en/geonames.json?q=toronto*

Among the result details and coordinates, it returns location and province of the result which helps to distinguish places with similar names:
![](https://i.imgur.com/m1QwNFS.png)

For postal code and coordinate searches, RAMP uses http://geogratis.gc.ca/services/geolocation/en/locate:
> http://geogratis.gc.ca/services/geolocation/en/locate?q=m8v*

Since this search is only returning the result name (it has the data in there, but it all fused in a single string), another `geonames.json` query is run to get the province and location name.

**Comment by mweech** [comment]
@AleksueiR watching the console, it appears as if RAMP takes the lat/long of the postal code query results from http://geogratis.gc.ca/services/geolocation/en/locate and then issues a lat/long search on geonames service.  This entire list of feature results is appended below the postal code which remains without a region noted.

**Comment by milesap** [comment]
Will add city/province to results returned

**Comment by milesap** [comment]
Changes in master branch. 

You can see the new iterator result object in the docs:
https://ramp-pcar.github.io/geosearch/#/demo1?id=result-object-passed-to-riterator
